package pages;

import org.junit.Assert;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;
import org.openqa.selenium.support.PageFactory;

public class OnlineRegistrationPage {

    public OnlineRegistrationPage(WebDriver driver) {
        PageFactory.initElements(driver, this);
    }

    @FindBy(how = How.LINK_TEXT, using = "South Africa")
    public WebElement linkSouthAfrica;

    @FindBy(how = How.XPATH, using = "//*/text()[.='CURRENT OPENINGS']/following::a")
    public WebElement linkTopOpening;

    @FindBy(how = How.XPATH, using = "//a[contains(text(),'Apply Online')]")
    public WebElement btnApplyOnline;

    @FindBy(how = How.ID, using = "applicant_name")
    public WebElement txtApplicantName;

    @FindBy(how = How.ID, using = "email")
    public WebElement txtEmail;

    @FindBy(how = How.ID, using = "phone")
    public WebElement txtPhone;

    @FindBy(how = How.XPATH, using = "//input[@value='Send Application']")
    public WebElement btnSend;

    @FindBy(how = How.XPATH, using = "//*[text()='You need to upload at least one file.']")
    public WebElement errorText;

    public void selectSouthAfrica() {
        try {
            linkSouthAfrica.click();
        } catch (Exception ex) {
            System.err.println("[Online Reg Page Object Error] Failed to select South Africa hyperlink, error - " + ex.getMessage());
        }
    }

    public void selectTopOpening() {
        try {
            linkTopOpening.click();
        } catch (Exception ex) {
            System.err.println("[Online Reg Page Object Error] Failed to select top job opening, error - " + ex.getMessage());
        }
    }

    public void selectApplyOnline() {
        try {
            btnApplyOnline.click();
        } catch (Exception ex) {
            System.err.println("[Online Reg Page Object Error] Failed to click Apply Online button, error - " + ex.getMessage());
        }
    }

    public void insertApplicantDetails(String firstName, String email) {
        try {

            System.out.println("[INFO] Inserting First Name");
            txtApplicantName.sendKeys(firstName);

            System.out.println("[INFO] Inserting Email Address");
            txtEmail.sendKeys(email);

        } catch (Exception ex) {
            System.err.println("[Online Reg Page Object Error] Failed to insert applicant details, error - " + ex.getMessage());
        }
    }

    public void insertAutoGeneratedPhoneNumber(String phone) {
        try {
            txtPhone.sendKeys(phone);
        } catch (Exception ex) {
            System.err.println("[Online Reg Page Object Error] Failed to insert auto-generated phone number, error - " + ex.getMessage());
        }
    }

    public void clickSendApplication() {
        try {
            btnSend.submit();
        } catch (Exception ex) {
            System.err.println("[Online Reg Page Object Error] Failed to click Send Application, error - " + ex.getMessage());
        }
    }

    public void verifyErrorTextDisplayed() {
        try {
            Assert.assertEquals("Error text not displayed on page", errorText.isDisplayed(), true);
        } catch (Exception ex) {
            System.err.println("[Online Reg Page Object Error] Failed verify error text, error - " + ex.getMessage());
        }
    }
}
